### ISSUE TITLE
Doesn't supported nested inline tags (marks)

### ISSUE THREAD

**Issue by Aaron3** [scrumpy/html-to-prosemirror#1]
For a simple document with marks spread across multiple tags, only the first node has the mark:

```html
<p>before link <a href="example.com">before em <em>em 1</em> <em>em 2</em> after ems in link</a> after link </p>
```

```json
{
	"type": "doc",
	"content": [{
		"type": "paragraph",
		"content": [{
				"type": "text",
				"text": "before link "
			},
			{
				"type": "text",
				"text": "before em ",
				"marks": [{
					"type": "link",
					"attrs": {
						"href": "example.com"
					}
				}]
			},
			{
				"type": "text",
				"text": "em 1",
				"marks": [{
					"type": "italic"
				}]
			},
			{
				"type": "text",
				"text": " "
			},
			{
				"type": "text",
				"text": "em 2",
				"marks": [{
					"type": "italic"
				}]
			},
			{
				"type": "text",
				"text": " after ems in link"
			},
			{
				"type": "text",
				"text": " after link"
			}
		]
	}]
}
```

The expected output is something like:

```json
{
	"type": "doc",
	"content": [{
		"type": "paragraph",
		"content": [{
				"type": "text",
				"text": "before link "
			},
			{
				"type": "text",
				"text": "before em ",
				"marks": [{
					"type": "link",
					"attrs": {
						"href": "example.com"
					}
				}]
			},
			{
				"type": "text",
				"text": "em 1",
				"marks": [{
					"type": "link",
					"attrs": {
						"href": "example.com"
					}
				},{
					"type": "italic"
				}]
			},
			{
				"type": "text",
				"text": " ",
				"marks": [{
					"type": "link",
					"attrs": {
						"href": "example.com"
					}
				}]
			},
			{
				"type": "text",
				"text": "em 2",
				"marks": [{
					"type": "link",
					"attrs": {
						"href": "example.com"
					}
				},{
					"type": "italic"
				}]
			},
			{
				"type": "text",
				"text": " after ems in link",
				"marks": [{
					"type": "link",
					"attrs": {
						"href": "example.com"
					}
				}]
			},
			{
				"type": "text",
				"text": " after link"
			}
		]
	}]
}
```

**Comment by hanspagel** [comment]
Confirmed, that's a bug. A simple test case:

**Input**

    <strong>right <em>wrong</em></strong>

**Output**

    {
        "type": "doc",
        "content": [
            {
                "type": "text",
                "text": "right ",
                "marks": [
                    {
                        "type": "bold"
                    }
                ]
            },
            {
                "type": "text",
                "text": "wrong",
                "marks": [
                    {
                        "type": "italic"
                    }
                ]
            }
        ]
    }

**Expected**

    {
        "type": "doc",
        "content": [
            {
                "type": "text",
                "text": "right ",
                "marks": [
                    {
                        "type": "bold"
                    }
                ]
            },
            {
                "type": "text",
                "text": "wrong",
                "marks": [
                    {
                        "type": "bold"
                    },                    
                    {
                        "type": "italic"
                    }
                ]
            }
        ]
    }

**Comment by hanspagel** [comment]
In `Renderer.php:104` storedMarks are reset:

    $this->storedMarks = [];

This should happen in most cases, but not in this case. Not sure about the solution yet. I'll think about it.

Thanks for reporting!
